# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/skaiuijing/NetStack

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/skaiuijing/NetStack

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skaiuijing/NetStack/CMakeFiles /home/skaiuijing/NetStack//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skaiuijing/NetStack/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NetStack

# Build rule for target.
NetStack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NetStack
.PHONY : NetStack

# fast build rule for target.
NetStack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/build
.PHONY : NetStack/fast

#=============================================================================
# Target rules for targets named cleanup

# Build rule for target.
cleanup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cleanup
.PHONY : cleanup

# fast build rule for target.
cleanup/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleanup.dir/build.make CMakeFiles/cleanup.dir/build
.PHONY : cleanup/fast

net/source/arp.o: net/source/arp.c.o
.PHONY : net/source/arp.o

# target to build an object file
net/source/arp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/arp.c.o
.PHONY : net/source/arp.c.o

net/source/arp.i: net/source/arp.c.i
.PHONY : net/source/arp.i

# target to preprocess a source file
net/source/arp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/arp.c.i
.PHONY : net/source/arp.c.i

net/source/arp.s: net/source/arp.c.s
.PHONY : net/source/arp.s

# target to generate assembly for a file
net/source/arp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/arp.c.s
.PHONY : net/source/arp.c.s

net/source/buf.o: net/source/buf.c.o
.PHONY : net/source/buf.o

# target to build an object file
net/source/buf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/buf.c.o
.PHONY : net/source/buf.c.o

net/source/buf.i: net/source/buf.c.i
.PHONY : net/source/buf.i

# target to preprocess a source file
net/source/buf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/buf.c.i
.PHONY : net/source/buf.c.i

net/source/buf.s: net/source/buf.c.s
.PHONY : net/source/buf.s

# target to generate assembly for a file
net/source/buf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/buf.c.s
.PHONY : net/source/buf.c.s

net/source/debug.o: net/source/debug.c.o
.PHONY : net/source/debug.o

# target to build an object file
net/source/debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/debug.c.o
.PHONY : net/source/debug.c.o

net/source/debug.i: net/source/debug.c.i
.PHONY : net/source/debug.i

# target to preprocess a source file
net/source/debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/debug.c.i
.PHONY : net/source/debug.c.i

net/source/debug.s: net/source/debug.c.s
.PHONY : net/source/debug.s

# target to generate assembly for a file
net/source/debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/debug.c.s
.PHONY : net/source/debug.c.s

net/source/ether.o: net/source/ether.c.o
.PHONY : net/source/ether.o

# target to build an object file
net/source/ether.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ether.c.o
.PHONY : net/source/ether.c.o

net/source/ether.i: net/source/ether.c.i
.PHONY : net/source/ether.i

# target to preprocess a source file
net/source/ether.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ether.c.i
.PHONY : net/source/ether.c.i

net/source/ether.s: net/source/ether.c.s
.PHONY : net/source/ether.s

# target to generate assembly for a file
net/source/ether.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ether.c.s
.PHONY : net/source/ether.c.s

net/source/icmp.o: net/source/icmp.c.o
.PHONY : net/source/icmp.o

# target to build an object file
net/source/icmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/icmp.c.o
.PHONY : net/source/icmp.c.o

net/source/icmp.i: net/source/icmp.c.i
.PHONY : net/source/icmp.i

# target to preprocess a source file
net/source/icmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/icmp.c.i
.PHONY : net/source/icmp.c.i

net/source/icmp.s: net/source/icmp.c.s
.PHONY : net/source/icmp.s

# target to generate assembly for a file
net/source/icmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/icmp.c.s
.PHONY : net/source/icmp.c.s

net/source/ifnet.o: net/source/ifnet.c.o
.PHONY : net/source/ifnet.o

# target to build an object file
net/source/ifnet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ifnet.c.o
.PHONY : net/source/ifnet.c.o

net/source/ifnet.i: net/source/ifnet.c.i
.PHONY : net/source/ifnet.i

# target to preprocess a source file
net/source/ifnet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ifnet.c.i
.PHONY : net/source/ifnet.c.i

net/source/ifnet.s: net/source/ifnet.c.s
.PHONY : net/source/ifnet.s

# target to generate assembly for a file
net/source/ifnet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ifnet.c.s
.PHONY : net/source/ifnet.c.s

net/source/in_cksum.o: net/source/in_cksum.c.o
.PHONY : net/source/in_cksum.o

# target to build an object file
net/source/in_cksum.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/in_cksum.c.o
.PHONY : net/source/in_cksum.c.o

net/source/in_cksum.i: net/source/in_cksum.c.i
.PHONY : net/source/in_cksum.i

# target to preprocess a source file
net/source/in_cksum.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/in_cksum.c.i
.PHONY : net/source/in_cksum.c.i

net/source/in_cksum.s: net/source/in_cksum.c.s
.PHONY : net/source/in_cksum.s

# target to generate assembly for a file
net/source/in_cksum.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/in_cksum.c.s
.PHONY : net/source/in_cksum.c.s

net/source/inpcb.o: net/source/inpcb.c.o
.PHONY : net/source/inpcb.o

# target to build an object file
net/source/inpcb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/inpcb.c.o
.PHONY : net/source/inpcb.c.o

net/source/inpcb.i: net/source/inpcb.c.i
.PHONY : net/source/inpcb.i

# target to preprocess a source file
net/source/inpcb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/inpcb.c.i
.PHONY : net/source/inpcb.c.i

net/source/inpcb.s: net/source/inpcb.c.s
.PHONY : net/source/inpcb.s

# target to generate assembly for a file
net/source/inpcb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/inpcb.c.s
.PHONY : net/source/inpcb.c.s

net/source/ip_input.o: net/source/ip_input.c.o
.PHONY : net/source/ip_input.o

# target to build an object file
net/source/ip_input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ip_input.c.o
.PHONY : net/source/ip_input.c.o

net/source/ip_input.i: net/source/ip_input.c.i
.PHONY : net/source/ip_input.i

# target to preprocess a source file
net/source/ip_input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ip_input.c.i
.PHONY : net/source/ip_input.c.i

net/source/ip_input.s: net/source/ip_input.c.s
.PHONY : net/source/ip_input.s

# target to generate assembly for a file
net/source/ip_input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ip_input.c.s
.PHONY : net/source/ip_input.c.s

net/source/ip_output.o: net/source/ip_output.c.o
.PHONY : net/source/ip_output.o

# target to build an object file
net/source/ip_output.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ip_output.c.o
.PHONY : net/source/ip_output.c.o

net/source/ip_output.i: net/source/ip_output.c.i
.PHONY : net/source/ip_output.i

# target to preprocess a source file
net/source/ip_output.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ip_output.c.i
.PHONY : net/source/ip_output.c.i

net/source/ip_output.s: net/source/ip_output.c.s
.PHONY : net/source/ip_output.s

# target to generate assembly for a file
net/source/ip_output.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/ip_output.c.s
.PHONY : net/source/ip_output.c.s

net/source/list.o: net/source/list.c.o
.PHONY : net/source/list.o

# target to build an object file
net/source/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/list.c.o
.PHONY : net/source/list.c.o

net/source/list.i: net/source/list.c.i
.PHONY : net/source/list.i

# target to preprocess a source file
net/source/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/list.c.i
.PHONY : net/source/list.c.i

net/source/list.s: net/source/list.c.s
.PHONY : net/source/list.s

# target to generate assembly for a file
net/source/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/list.c.s
.PHONY : net/source/list.c.s

net/source/memalloc.o: net/source/memalloc.c.o
.PHONY : net/source/memalloc.o

# target to build an object file
net/source/memalloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/memalloc.c.o
.PHONY : net/source/memalloc.c.o

net/source/memalloc.i: net/source/memalloc.c.i
.PHONY : net/source/memalloc.i

# target to preprocess a source file
net/source/memalloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/memalloc.c.i
.PHONY : net/source/memalloc.c.i

net/source/memalloc.s: net/source/memalloc.c.s
.PHONY : net/source/memalloc.s

# target to generate assembly for a file
net/source/memalloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/memalloc.c.s
.PHONY : net/source/memalloc.c.s

net/source/mempool.o: net/source/mempool.c.o
.PHONY : net/source/mempool.o

# target to build an object file
net/source/mempool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/mempool.c.o
.PHONY : net/source/mempool.c.o

net/source/mempool.i: net/source/mempool.c.i
.PHONY : net/source/mempool.i

# target to preprocess a source file
net/source/mempool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/mempool.c.i
.PHONY : net/source/mempool.c.i

net/source/mempool.s: net/source/mempool.c.s
.PHONY : net/source/mempool.s

# target to generate assembly for a file
net/source/mempool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/mempool.c.s
.PHONY : net/source/mempool.c.s

net/source/queue.o: net/source/queue.c.o
.PHONY : net/source/queue.o

# target to build an object file
net/source/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/queue.c.o
.PHONY : net/source/queue.c.o

net/source/queue.i: net/source/queue.c.i
.PHONY : net/source/queue.i

# target to preprocess a source file
net/source/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/queue.c.i
.PHONY : net/source/queue.c.i

net/source/queue.s: net/source/queue.c.s
.PHONY : net/source/queue.s

# target to generate assembly for a file
net/source/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/queue.c.s
.PHONY : net/source/queue.c.s

net/source/route.o: net/source/route.c.o
.PHONY : net/source/route.o

# target to build an object file
net/source/route.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/route.c.o
.PHONY : net/source/route.c.o

net/source/route.i: net/source/route.c.i
.PHONY : net/source/route.i

# target to preprocess a source file
net/source/route.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/route.c.i
.PHONY : net/source/route.c.i

net/source/route.s: net/source/route.c.s
.PHONY : net/source/route.s

# target to generate assembly for a file
net/source/route.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/route.c.s
.PHONY : net/source/route.c.s

net/source/socket.o: net/source/socket.c.o
.PHONY : net/source/socket.o

# target to build an object file
net/source/socket.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/socket.c.o
.PHONY : net/source/socket.c.o

net/source/socket.i: net/source/socket.c.i
.PHONY : net/source/socket.i

# target to preprocess a source file
net/source/socket.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/socket.c.i
.PHONY : net/source/socket.c.i

net/source/socket.s: net/source/socket.c.s
.PHONY : net/source/socket.s

# target to generate assembly for a file
net/source/socket.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/socket.c.s
.PHONY : net/source/socket.c.s

net/source/tapif.o: net/source/tapif.c.o
.PHONY : net/source/tapif.o

# target to build an object file
net/source/tapif.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tapif.c.o
.PHONY : net/source/tapif.c.o

net/source/tapif.i: net/source/tapif.c.i
.PHONY : net/source/tapif.i

# target to preprocess a source file
net/source/tapif.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tapif.c.i
.PHONY : net/source/tapif.c.i

net/source/tapif.s: net/source/tapif.c.s
.PHONY : net/source/tapif.s

# target to generate assembly for a file
net/source/tapif.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tapif.c.s
.PHONY : net/source/tapif.c.s

net/source/tcp_input.o: net/source/tcp_input.c.o
.PHONY : net/source/tcp_input.o

# target to build an object file
net/source/tcp_input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_input.c.o
.PHONY : net/source/tcp_input.c.o

net/source/tcp_input.i: net/source/tcp_input.c.i
.PHONY : net/source/tcp_input.i

# target to preprocess a source file
net/source/tcp_input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_input.c.i
.PHONY : net/source/tcp_input.c.i

net/source/tcp_input.s: net/source/tcp_input.c.s
.PHONY : net/source/tcp_input.s

# target to generate assembly for a file
net/source/tcp_input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_input.c.s
.PHONY : net/source/tcp_input.c.s

net/source/tcp_output.o: net/source/tcp_output.c.o
.PHONY : net/source/tcp_output.o

# target to build an object file
net/source/tcp_output.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_output.c.o
.PHONY : net/source/tcp_output.c.o

net/source/tcp_output.i: net/source/tcp_output.c.i
.PHONY : net/source/tcp_output.i

# target to preprocess a source file
net/source/tcp_output.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_output.c.i
.PHONY : net/source/tcp_output.c.i

net/source/tcp_output.s: net/source/tcp_output.c.s
.PHONY : net/source/tcp_output.s

# target to generate assembly for a file
net/source/tcp_output.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_output.c.s
.PHONY : net/source/tcp_output.c.s

net/source/tcp_suber.o: net/source/tcp_suber.c.o
.PHONY : net/source/tcp_suber.o

# target to build an object file
net/source/tcp_suber.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_suber.c.o
.PHONY : net/source/tcp_suber.c.o

net/source/tcp_suber.i: net/source/tcp_suber.c.i
.PHONY : net/source/tcp_suber.i

# target to preprocess a source file
net/source/tcp_suber.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_suber.c.i
.PHONY : net/source/tcp_suber.c.i

net/source/tcp_suber.s: net/source/tcp_suber.c.s
.PHONY : net/source/tcp_suber.s

# target to generate assembly for a file
net/source/tcp_suber.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_suber.c.s
.PHONY : net/source/tcp_suber.c.s

net/source/tcp_timer.o: net/source/tcp_timer.c.o
.PHONY : net/source/tcp_timer.o

# target to build an object file
net/source/tcp_timer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_timer.c.o
.PHONY : net/source/tcp_timer.c.o

net/source/tcp_timer.i: net/source/tcp_timer.c.i
.PHONY : net/source/tcp_timer.i

# target to preprocess a source file
net/source/tcp_timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_timer.c.i
.PHONY : net/source/tcp_timer.c.i

net/source/tcp_timer.s: net/source/tcp_timer.c.s
.PHONY : net/source/tcp_timer.s

# target to generate assembly for a file
net/source/tcp_timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/tcp_timer.c.s
.PHONY : net/source/tcp_timer.c.s

net/source/udp.o: net/source/udp.c.o
.PHONY : net/source/udp.o

# target to build an object file
net/source/udp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/udp.c.o
.PHONY : net/source/udp.c.o

net/source/udp.i: net/source/udp.c.i
.PHONY : net/source/udp.i

# target to preprocess a source file
net/source/udp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/udp.c.i
.PHONY : net/source/udp.c.i

net/source/udp.s: net/source/udp.c.s
.PHONY : net/source/udp.s

# target to generate assembly for a file
net/source/udp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/net/source/udp.c.s
.PHONY : net/source/udp.c.s

testfile/test.o: testfile/test.c.o
.PHONY : testfile/test.o

# target to build an object file
testfile/test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/testfile/test.c.o
.PHONY : testfile/test.c.o

testfile/test.i: testfile/test.c.i
.PHONY : testfile/test.i

# target to preprocess a source file
testfile/test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/testfile/test.c.i
.PHONY : testfile/test.c.i

testfile/test.s: testfile/test.c.s
.PHONY : testfile/test.s

# target to generate assembly for a file
testfile/test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetStack.dir/build.make CMakeFiles/NetStack.dir/testfile/test.c.s
.PHONY : testfile/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cleanup"
	@echo "... NetStack"
	@echo "... net/source/arp.o"
	@echo "... net/source/arp.i"
	@echo "... net/source/arp.s"
	@echo "... net/source/buf.o"
	@echo "... net/source/buf.i"
	@echo "... net/source/buf.s"
	@echo "... net/source/debug.o"
	@echo "... net/source/debug.i"
	@echo "... net/source/debug.s"
	@echo "... net/source/ether.o"
	@echo "... net/source/ether.i"
	@echo "... net/source/ether.s"
	@echo "... net/source/icmp.o"
	@echo "... net/source/icmp.i"
	@echo "... net/source/icmp.s"
	@echo "... net/source/ifnet.o"
	@echo "... net/source/ifnet.i"
	@echo "... net/source/ifnet.s"
	@echo "... net/source/in_cksum.o"
	@echo "... net/source/in_cksum.i"
	@echo "... net/source/in_cksum.s"
	@echo "... net/source/inpcb.o"
	@echo "... net/source/inpcb.i"
	@echo "... net/source/inpcb.s"
	@echo "... net/source/ip_input.o"
	@echo "... net/source/ip_input.i"
	@echo "... net/source/ip_input.s"
	@echo "... net/source/ip_output.o"
	@echo "... net/source/ip_output.i"
	@echo "... net/source/ip_output.s"
	@echo "... net/source/list.o"
	@echo "... net/source/list.i"
	@echo "... net/source/list.s"
	@echo "... net/source/memalloc.o"
	@echo "... net/source/memalloc.i"
	@echo "... net/source/memalloc.s"
	@echo "... net/source/mempool.o"
	@echo "... net/source/mempool.i"
	@echo "... net/source/mempool.s"
	@echo "... net/source/queue.o"
	@echo "... net/source/queue.i"
	@echo "... net/source/queue.s"
	@echo "... net/source/route.o"
	@echo "... net/source/route.i"
	@echo "... net/source/route.s"
	@echo "... net/source/socket.o"
	@echo "... net/source/socket.i"
	@echo "... net/source/socket.s"
	@echo "... net/source/tapif.o"
	@echo "... net/source/tapif.i"
	@echo "... net/source/tapif.s"
	@echo "... net/source/tcp_input.o"
	@echo "... net/source/tcp_input.i"
	@echo "... net/source/tcp_input.s"
	@echo "... net/source/tcp_output.o"
	@echo "... net/source/tcp_output.i"
	@echo "... net/source/tcp_output.s"
	@echo "... net/source/tcp_suber.o"
	@echo "... net/source/tcp_suber.i"
	@echo "... net/source/tcp_suber.s"
	@echo "... net/source/tcp_timer.o"
	@echo "... net/source/tcp_timer.i"
	@echo "... net/source/tcp_timer.s"
	@echo "... net/source/udp.o"
	@echo "... net/source/udp.i"
	@echo "... net/source/udp.s"
	@echo "... testfile/test.o"
	@echo "... testfile/test.i"
	@echo "... testfile/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

